import '../style/globals.css'
import { Poppins} from 'next/font/google'

export const poppins = Poppins({
   weight: "500",
   subsets: ["latin"],
   variable: '--font-poppins'
})
export const poppins_bold = Poppins({
   weight: "700",
   subsets: ["latin"],
   variable: '--font-poppins_bold'
})



export const metadata = {
  title: 'url-shortening',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className }>{children}</body>
    </html>
  )
}
